---

- name: load actual public host key
  register: ssh_public_key_file
  ansible.builtin.slurp:
    src: "/etc/ssh/{{ sshd_certfile }}.pub"

- name: debug public host key
  ansible.builtin.debug:
    var: ssh_public_key_file

- name: debug public host key content
  ansible.builtin.debug:
    msg: "{{ ssh_public_key_file['content'] | b64decode }}"

- name: set fact about public host key
  ansible.builtin.set_fact:
    ssh_public_key: "{{ ssh_public_key_file['content'] | b64decode }}"

- name: generate signed host key
  register: signed_host_key
  delegate_to: localhost
  become: false
  community.hashi_vault.vault_write:
    path: "{{ host_ssh_path }}/sign/{{ host_ssh_role }}"
    token: "{{ vault_token }}"
    data:
      cert_type: host
      public_key: "{{ ssh_public_key }}"

- name: debug signed host key
  ansible.builtin.debug:
    var: signed_host_key

- name: update signed host key certificate
  become: true
  ansible.builtin.copy:
    content: "{{ signed_host_key.data.data.signed_key }}"
    dest: "/etc/ssh/{{ sshd_certfile }}_signed.pub"
    mode: "0640"
    owner: root
    group: root
  notify:
    - restart sshd

- name: fail on purpose if signed host key is not available
  ansible.builtin.fail:
    msg: "Stop it!"
  

- name: ensure ssh config with enabled host key
  become: true
  ansible.builtin.lineinfile:
    regexp: "^HostKey"
    line: "HostKey /etc/ssh/{{ sshd_certfile }}"
    dest: /etc/ssh/sshd_config
    mode: "0640"
  notify:
    - restart sshd

- name: update ssh config with signed host certificate from vault
  become: true
  ansible.builtin.lineinfile:
    regexp: "^HostCertificate"
    line: "HostCertificate /etc/ssh/{{ sshd_certfile }}_signed.pub"
    dest: /etc/ssh/sshd_config
    mode: "0640"
  notify:
    - restart sshd

- name: load trusted ca from vault
  register: vault_trusted_keys
  delegate_to: localhost
  become: false
  community.hashi_vault.vault_read:
    path: "{{ host_ssh_path }}/config/ca"
    token: "{{ vault_token }}"

- name: ensure .ssh directory exists
  become: false
  ansible.builtin.file:
    path: ~/.ssh/
    state: directory

- name: add trust authority configuration
  become: false
  ansible.builtin.copy:
    content: |
      {% for domain in cert_authority_domains %}
      @cert-authority {{ domain }} {{ vault_trusted_keys.data.data.public_key }}
      {% endfor %}
    dest: ~/.ssh/known_hosts
    mode: "0644"
