---

- name: Login to vault with approle
  when: vault_host_secret_id is defined and vault_host_role_id is defined and vault_host_secret_id | length > 0 and vault_host_role_id | length > 0
  block:
  - name: Login approle
    delegate_to: localhost
    become: false
    register: login_data
    community.hashi_vault.vault_login:
      auth_method: approle
      mount_point: pipeline_approle
      role_id: "{{ vault_host_role_id }}"
      secret_id: "{{ vault_host_secret_id }}"

  - name: "Vault - set vault token"
    ansible.builtin.set_fact:
      vault_token: '{{ login_data.login.auth.client_token }}'

- ansible.builtin.include_tasks: user_keys.yml
  when: user_ssh_path is defined

- ansible.builtin.include_tasks: host_keys.yml
  when: host_ssh_path is defined
