---
- name: load trusted ca from vault
  register: vault_trusted_keys
  delegate_to: localhost
  become: false
  community.hashi_vault.vault_read:
    path: "{{ host_ssh_path }}/config/ca"
    token: "{{ vault_token }}"

- name: ensure .ssh directory exists
  become: false
  ansible.builtin.file:
    path: ~/.ssh/
    state: directory

- name: add trust authority configuration
  become: false
  ansible.builtin.copy:
    content: |
      {% for domain in cert_authority_domains %}
      @cert-authority {{ domain }} {{ vault_trusted_keys.data.data.public_key }}
      {% endfor %}
    dest: ~/.ssh/known_hosts
    mode: "0644"

- name: add trust authority configuration
  become: true
  ansible.builtin.copy:
    content: |
      {% for domain in cert_authority_domains %}
      @cert-authority {{ domain }} {{ vault_trusted_keys.data.data.public_key }}
      {% endfor %}
    dest: ~/.ssh/known_hosts
    mode: "0644"
