---
- name: load trusted ca from vault
  register: vault_trusted_keys
  delegate_to: localhost
  become: false
  community.hashi_vault.vault_read:
    path: "{{ user_ssh_path }}/config/ca"
    token: "{{ vault_token }}"

- name: debug
  debug: var=vault_trusted_keys

- name: store trusted ca keys
  copy:
    content: "{{ vault_trusted_keys.data.data.public_key }}"
    dest: "/etc/ssh/trusted-user-ca-keys.pub"
    owner: root
    group: root
    mode: 0640

- name: update ssh config with trusted user ca
  lineinfile:
    regexp: "^TrustedUserCAKeys"
    line: "TrustedUserCAKeys /etc/ssh/trusted-user-ca-keys.pub"
    dest: /etc/ssh/sshd_config
    mode: 0640
  notify:
    - restart sshd

- name: ensure ssh-rsa algorithm is allowed for ca signatures
  lineinfile:
    regexp: "^CASignatureAlgorithms"
    line: "CASignatureAlgorithms ^ssh-rsa"
    dest: /etc/ssh/sshd_config
    mode: 0640
  notify:
    - restart sshd

