---
- name: load trusted ca from vault
  register: vault_trusted_keys
  delegate_to: localhost
  become: false
  community.hashi_vault.vault_read:
    path: "{{ user_ssh_path }}/config/ca"
    token: "{{ vault_token }}"

- name: store trusted ca keys
  become: true
  ansible.builtin.copy:
    content: "{{ vault_trusted_keys.data.data.public_key }}"
    dest: "{{ ssh_config_dir }}/{{ sshd_signed_certfile }}"
    owner: root
    group: root
    mode: "0640"

- name: update ssh config with trusted user ca
  become: true
  ansible.builtin.lineinfile:
    regexp: "^TrustedUserCAKeys"
    line: "TrustedUserCAKeys {{ ssh_config_dir }}/{{ sshd_signed_certfile }}"
    dest: "{{ ssh_config_dir }}/sshd_config"
    mode: "0640"
  notify:
    - restart sshd
